// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

const SUPABASE_URL = 'https://qzdvbpmfjooncqginvze.supabase.co'
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6ZHZicG1mam9vbmNxZ2ludnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTc3MDMsImV4cCI6MjA2ODQzMzcwM30.s98ZtsfmT6RzYQQ9lMh-FVnBupMyK13DctQtABf-Ras'

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
)
